### ISSUE TITLE
Is it due to the missing of a file or there's an issue with the dataset processing?

### ISSUE THREAD

**Issue by HSC472** [elchun/contact_graspnet_pytorch#1]
作者你好，感谢你提供contact-graspnet的pytorch实现，我是该抓取领域的新手，在复现您的代码时，出现了报错，该报错为：“FileNotFoundError: [Errno 2] No such file or directory: 'acronym/renders”，似乎在acronym文件夹下面还应当有一个renders文件或者文件夹。
    当我把这两行代码修改为：“train_dataset = AcryonymDataset(global_config, train=True, device=device, use_saved_renders=False)
    test_dataset = AcryonymDataset(global_config, train=False, device=device, use_saved_renders=False)”，出现了新的报错：“ValueError: __len__() should return >= 0”，可能原因是：‘len(datdset)<0’。这是否意味着我的acronym数据集没有处理好？

Hello, the author. Thank you for providing the PyTorch implementation of contact-graspnet. I am a beginner in the grasping field and encountered an error when trying to reproduce your code. The error message is: "FileNotFoundError: [Errno 2] No such file or directory: 'acronym/renders'". It seems that there should be a renders file or folder under the 'acronym' folder as well.

When I changed the two lines of code to: "train_dataset = AcryonymDataset(global_config, train=True, device=device, use_saved_renders=False)
test_dataset = AcryonymDataset(global_config, train=False, device=device, use_saved_renders=False)", a new error appeared: "ValueError: len() should return >= 0". The possible reason is that 'len(datdset)<0'. Does this mean that my acronym dataset has not been processed properly?

**Comment by elchun** [comment]
Hi @HSC472, thank you for your interest.  This error is caused by the directory `acronym/renders` not existing.  I have modified the dataset script to automatically generate this directory which should fix your issue.  I have also included a set of weights under `checkpoints/contact_graspnet/checkpoints` which should allow you to run the `inference.py` script as well.  Feel free to reach out if you have any additional questions.

**Comment by HSC472** [comment]
Thank you very much for your help. I can successfully run your code and use your pth for inference. However, there may be a problem with the construction of the dataset. When running the waterproof_meshes.py script, 68 failures were recorded in the acronym/failed.txt file. When I trained, many errors like this were output: "Error loading scene 003235
Could not load mesh from filename:/home/ubuntu/code/CGN_torch/acronym/meshes/Dog/feb146982d0c64dfcbf4f3f04bbad8.obj".

Since I have been unable to solve these problems, I will try new code. Finally, thank you again.

**Comment by elchun** [comment]
Yes, the waterproofing tends to be very touchy.  We found that we could still train by removing any meshes that failed to waterproof, although this is not ideal.  Best of luck with other models!
