### ISSUE TITLE
The inferencing results are weird

### ISSUE THREAD

**Issue by CaptainWuDaoKou** [elchun/contact_graspnet_pytorch#2]
Hi, thank for your pytorch implementation of Contact Graspnet.  One of the problems I ran into was that the prediction was weird and completely disorganized. 
<img width="520" alt="微信图片_20240124111604" src="https://github.com/elchun/contact_graspnet_pytorch/assets/50624671/bf4b729a-a78f-4192-8027-aec7e1d0f62d">

Someone had a similar problem with the official TensorFlow version and needed to recompile the "tf_ops" file. What should I do to fix this?  Thanks

**Comment by AstroTheKat** [comment]
@CaptainWuDaoKou what did you end up doing to fix this? Thanks!

**Comment by CaptainWuDaoKou** [comment]
> @CaptainWuDaoKou what did you end up doing to fix this? Thanks!

It's kind of a dumb problem as I forgot to load the model weights.
